component input search
TimKelompok5/mobile-app pull request #41
Opened 2022-11-21 18:39 UTC by masherrs

semoga bener

2022-11-22 03:19 UTC, triandamai requested changes
Butuh callback ketika user ngetik buat dapetin apa yang user ketik

Harusnya jadi seperti ini:
```dart
InputSearch(
 label:"Input nama",
  onChange:(value){
      //hasil yang di ketik
 }
)

```
Sekarang cuma bisa:
```dart
InputSearch()

```

Kata kunci di google: "how to add parameter function in flutter"

2022-11-22 03:19 UTC, triandamai commented
Tanya @marioprasetyo buat contoh dia udah bisa bikin parameter callback

2022-11-22 10:20 UTC, masherrs commented
Oke repisi

2022-11-22 11:04 UTC, triandamai requested changes
Di cek lagi ya

2022-11-23 09:29 UTC, triandamai commented on lib/components/input_search.dart
> +
Ini mana ya parameter label sama hint

2022-11-23 09:29 UTC, triandamai requested changes
Ceh lagi ya

2022-11-24 02:37 UTC, triandamai approved these changes
Lgtm

2022-11-24 02:37 UTC, merged