page home
TimKelompok5/mobile-app pull request #67
Opened 2022-11-28 10:14 UTC by marioprasetyo

2022-11-28 13:44 UTC, triandamai commented
convoy
```dart

new NestedScrollView(
        body: new Column(
          children: <Widget>[
            new Container(
              height: 300.0,
              child: new ListView.builder(
                itemCount: 60,//jumlah data 
                itemBuilder: (BuildContext context, int index) {
 
                  return ItemContinueListening();
                },
              ),
            ),
            new Container(
              height: 300.0,
              child: new ListView.builder(
                itemCount: 60,
                itemBuilder: (BuildContext context, int index) {
                  return ItemEpisode();
                },
              ),
            ),

          ],
        ),
      )
```

2022-11-28 13:44 UTC, triandamai requested changes
repisi

2022-11-29 04:53 UTC, marioprasetyo commented
belom paham mas

2022-11-29 14:50 UTC, triandamai commented on lib/components/card_audiobook.dart
> +
onClick

2022-11-29 14:51 UTC, triandamai commented on lib/components/card_continuelistening.dart
onClick

2022-11-29 14:51 UTC, triandamai commented on lib/components/card_episode.dart
>    final String name;
onClick

2022-11-29 14:56 UTC, merged